In [8]:
import pandas as pd
from sklearn.externals import joblib
from sklearn.preprocessing import LabelEncoder
import numpy as np

df = pd.read_csv("./us_perm_visas_to_classification.csv", low_memory=False)
X = df.loc[:, df.columns != 'case_status']
x = X.values
Y = df.case_status
y = Y.values

np.save("data.npy", x)
np.save("label.npy", y)


'\ndf = pd.read_csv("./us_perm_visas_to_classification.csv", low_memory=False)\nX = df.loc[:, df.columns != \'case_status\']\nx = X.values\nY = df.case_status\ny = Y.values\n\nnp.save("data.npy", x)\nnp.save("label.npy", y)\n\nprint ("Data Done.")\n'

In [9]:
x = np.load("data.npy")
y = np.load("label.npy")
print (x.shape, y.shape)

(356168, 8) (356168,)


In [10]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

print ("Start")

kf = StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

idx = 0
for train_index, test_index in kf.split(x, y):
    print (idx)
    train = x[train_index, :]
    trainLabel = y[train_index]
    test = x[test_index, :]
    testLabel = y[test_index]
    
    knn = KNeighborsClassifier(n_neighbors = 1)
    knn.fit(train, trainLabel) 
    preTrainLabel = knn.predict(train)
    
    print ("Train")
    print (confusion_matrix(trainLabel, preTrainLabel))
    
    preTestLabel = knn.predict(test)
    
    print ("Test")
    print (confusion_matrix(testLabel, preTestLabel))
    
    #testProb = knn.predict_proba(test)
    #print (testProb.shape)
    #print (testProb[0, :], preTestLabel[0])
    
    idx += 1


Start
0
Train
[[ 17099      0]
 [     0 220346]]
Test
[[     0   8550]
 [     0 110173]]
1
Train
[[ 17099      0]
 [     0 220346]]
Test
[[ 3928  4622]
 [95882 14291]]
2
Train
[[ 17100      0]
 [     0 220346]]
Test
[[     0   8549]
 [     0 110173]]


In [11]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

print ("Start")

kf = StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

idx = 0
for train_index, test_index in kf.split(x, y):
    print (idx)
    train = x[train_index, :]
    trainLabel = y[train_index]
    test = x[test_index, :]
    testLabel = y[test_index]
    
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(train, trainLabel) 
    preTrainLabel = knn.predict(train)
    
    print ("Train")
    print (confusion_matrix(trainLabel, preTrainLabel))
    
    preTestLabel = knn.predict(test)
    
    print ("Test")
    print (confusion_matrix(testLabel, preTestLabel))
    
    #testProb = knn.predict_proba(test)
    #print (testProb.shape)
    #print (testProb[0, :], preTestLabel[0])
    
    idx += 1


Start
0
Train
[[  9709   7390]
 [  1186 219160]]
Test
[[     0   8550]
 [     0 110173]]
1
Train
[[ 11660   5439]
 [   970 219376]]
Test
[[  884  7666]
 [81767 28406]]
2
Train
[[ 13242   3858]
 [   952 219394]]
Test
[[     0   8549]
 [     0 110173]]


In [12]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

print ("Start")

kf = StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

idx = 0
for train_index, test_index in kf.split(x, y):
    print (idx)
    train = x[train_index, :]
    trainLabel = y[train_index]
    test = x[test_index, :]
    testLabel = y[test_index]
    
    knn = KNeighborsClassifier(n_neighbors = 5)
    knn.fit(train, trainLabel) 
    preTrainLabel = knn.predict(train)
    
    print ("Train")
    print (confusion_matrix(trainLabel, preTrainLabel))
    
    preTestLabel = knn.predict(test)
    
    print ("Test")
    print (confusion_matrix(testLabel, preTestLabel))
    
    #testProb = knn.predict_proba(test)
    #print (testProb.shape)
    #print (testProb[0, :], preTestLabel[0])
    
    idx += 1


Start
0
Train
[[  8251   8848]
 [  1093 219253]]
Test
[[     0   8550]
 [     0 110173]]
1
Train
[[ 10458   6641]
 [   854 219492]]
Test
[[  882  7668]
 [81507 28666]]
2
Train
[[ 12411   4689]
 [   905 219441]]
Test
[[     0   8549]
 [     0 110173]]


In [13]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold

print ("Start")

kf = StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

idx = 0
for train_index, test_index in kf.split(x, y):
    print (idx)
    train = x[train_index, :]
    trainLabel = y[train_index]
    test = x[test_index, :]
    testLabel = y[test_index]
    
    knn = KNeighborsClassifier(n_neighbors = 7)
    knn.fit(train, trainLabel) 
    preTrainLabel = knn.predict(train)
    
    print ("Train")
    print (confusion_matrix(trainLabel, preTrainLabel))
    
    preTestLabel = knn.predict(test)
    
    print ("Test")
    print (confusion_matrix(testLabel, preTestLabel))
    
    #testProb = knn.predict_proba(test)
    #print (testProb.shape)
    #print (testProb[0, :], preTestLabel[0])
    
    idx += 1


Start
0
Train
[[  7680   9419]
 [   994 219352]]
Test
[[     0   8550]
 [     0 110173]]
1
Train
[[  9902   7197]
 [   723 219623]]
Test
[[  877  7673]
 [81347 28826]]
2
Train
[[ 12070   5030]
 [   858 219488]]
Test
[[     0   8549]
 [     0 110173]]
